apiVersion: v1
kind: ReplicationController
metadata:
    name: whoami
spec:
    replicas: 3
    selector:
        app: whoami
    template:
        metadata:
            name: whoami
            labels:
                app: whoami
                env: dev
        spec:
            containers:
            -   name: whoami
                image: cizixs/whoami:v0.5
                ports:
                -   containerPort: 3000
                env:
                -   name: MESSAGE
                    value: viola

