version: "2"
services:
    etcd:
        image: elcolio/etcd
        volumes:
        -   /usr/share/ca-certificates/:/etc/ssl/certs:ro
        -   ./.etcd:/data
        network_mode: host
        command:
        -   --name=node-10.70.1.31
        -   --advertise-client-urls=http://10.70.1.31:2379,http://10.70.1.31:4001
        -   --listen-client-urls=http://0.0.0.0:2379,http://0.0.0.0:4001
        -   --initial-advertise-peer-urls=http://10.70.1.31:2380
        -   --listen-peer-urls=http://0.0.0.0:2380
        -   --discovery=http://discovery.etcd.io/2734d6ced01b2e58165f20db5d80fb72
        -   --initial-cluster-state=new
